# Generated by Django 5.1.3 on 2024-12-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heiwa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
