# Generated by Django 5.1.3 on 2024-12-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heiwa', '0002_mesa_alter_order_mesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='numeroMesa',
        ),
    ]
