# Generated by Django 5.1.3 on 2024-12-11 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heiwa', '0002_mesa_alter_order_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='heiwa.mesa'),
        ),
    ]
