# Generated by Django 5.1.3 on 2024-12-12 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heiwa', '0003_alter_order_mesa'),
        ('heiwa', '0003_remove_mesa_numeromesa'),
    ]

    operations = [
    ]
